In [13]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\navan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\navan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\navan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\navan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\navan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\navan\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [15]:
import pandas as pd
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=["A","B","C"], index=["x","y","z"])
df.head() # we can flow a index inside the head(" ") to get the value from 0th index to till passed

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [16]:
df.tail(2) # we can flow a index inside the Tail(" ") to get the value from last index to till passed in reverse

   A  B  C
y  4  5  6
z  7  8  9

In [17]:
df.columns  # displays colums and the dtype of the variables in column

Index(['A', 'B', 'C'], dtype='str')

In [18]:
df.index  # displays rows and the dtype of the variables in row

Index(['x', 'y', 'z'], dtype='str')

In [19]:
x=df.index.tolist()  # we can represent as list by using tolist 
y=df.columns.tolist()
print(x)
print(y)

['x', 'y', 'z']
['A', 'B', 'C']

In [20]:
df.info()   # displays the info of an dataframe

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 99.0 bytes

In [21]:
df.describe()  # gives the info about the values with there respected percentages

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [22]:
df.shape # diaplys the shape of an DataFrame (rows,columns)

(3, 3)

In [23]:
df.size   # size of an DataFrame

9

LOADING DATASETS

In [3]:
coffee=pd.read_csv('../data/coffee.csv')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [6]:

results=pd.read_parquet('../data/results.parquet', engine='fastparquet')

In [7]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [9]:

olympics_data=pd.read_excel('../data/olympics-data.xlsx')

In [10]:
olympics_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [11]:
bios=pd.read_csv('../data/bios.csv')

In [12]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

ACCESSING DATA WITH PANDAS

In [31]:
coffee.head(10)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45
9     Friday       Latte          35

In [32]:
coffee.tail(5)

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [34]:
coffee.sample(10) # randomly select the data among dataset in the csv file

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
4   Wednesday    Espresso          35
10   Saturday    Espresso          45
6    Thursday    Espresso          40
9      Friday       Latte          35
12     Sunday    Espresso          45
2     Tuesday    Espresso          30
7    Thursday       Latte          30
13     Sunday       Latte          35
0      Monday    Espresso          25

In [ ]:
coffee.loc[[1,7]] # we can select the data by using loc and passing the index of the data we want to select

        Day Coffee Type  Units Sold
1    Monday       Latte          15
7  Thursday       Latte          30

In [ ]:
coffee.loc[5:10] # we can use slicing to retrieve the data from index ranges

          Day Coffee Type  Units Sold
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45

In [40]:
coffee.loc[5:9,["Day","Units Sold"]] # we can use slicing to retrieve the data from index ranges and also we can pass the column name to get the specific column data

         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30
8     Friday          45
9     Friday          35

In [43]:
coffee.iloc[:,[0,2]] # [[selective rows index],[selective column index]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [46]:
# we can modify the data by using loc and iloc and passing the index of the data we want to modify and also we can pass the column name to get the specific column data and then we can assign the new value to it
coffee.loc[1,"Units Sold"]=20
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1         25       Latte          20
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [ ]:
# at-> gives an single value based on the reqiured index and column name
coffee.at[1,"Units Sold"]

np.int64(20)

In [ ]:
# iat-> gives an single value based on the reqiured index and column index
coffee.iat[0,1]

'Espresso'

In [55]:
coffee.sort_values(["Units Sold","Coffee Type"], ascending=True) # we can sort the values by using sort_values and passing the column name and also we can pass the ascending as False to sort in descending order

          Day Coffee Type  Units Sold
1      Monday       Latte          15
3     Tuesday       Latte          20
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          30
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [5]:
for index,row in coffee.iterrows():
    print(row['Units Sold'])
    print(index)
    print("\n")

25
0


15
1


30
2


20
3


35
4


25
5


40
6


30
7


45
8


35
9


45
10


35
11


45
12


35
13

FILTERING DATA

In [14]:
bios.tail()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [16]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 18.5 MB

In [ ]:
bios.loc[bios['height_cm']>215,['name','height_cm']]   # we can display data based on certain constraints and conditions

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [23]:
bios[(bios['height_cm'] > 215) & (bios['born_country'] == 'USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [ ]:
bios[bios['born_country'].str.contains('USA|',case=False)] # we can access the data with column name and the word

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1670,1677,Freddy Rojas,1969-08-27,Camagüey,Camagüey,CUB,Cuba,192.0,81.0,NaN
4001,4015,Ando Reddy,1933-01-18,Dublin,Dublin,IRL,Ireland,155.0,58.0,2022-03-06
4002,4016,Tommy Reddy,1929-07-23,NaN,NaN,NaN,Ireland,NaN,NaN,1992-05-27
15322,15427,Freddy Maertens,1952-02-13,Lombardsijde,West-Vlaanderen,BEL,Belgium,174.0,71.0,NaN
17530,17650,Freddy Cattoir,1906-10-27,Ixelles,Région de Bruxelles-Capitale,BEL,Belgium,NaN,NaN,1984-02-16
17592,17712,Freddy Rens,1936-12-25,Bruxelles (Brussels),Région de Bruxelles-Capitale,BEL,Belgium,178.0,70.0,NaN
19501,19640,Freddy Vias,1929-10-08,Seremban,Negeri Sembilan,MAS,Malaya,NaN,NaN,2022-06-07
22154,22318,Freddy Scholz,1961-09-14,Düsseldorf,Nordrhein-Westfalen,GER,West Germany,183.0,74.0,NaN
23655,23839,Freddy Quintero,1938-05-24,Caracas,Distrito Capital,VEN,Venezuela,170.0,68.0,NaN
23657,23841,Freddy Salazar,1949-04-11,Caracas,Distrito Capital,VEN,Venezuela,175.0,75.0,NaN
25000,25190,Freddy Zix,1935-01-07,Strasbourg,Bas-Rhin,FRA,France,178.0,76.0,NaN
29426,29646,Freddy Jensen,1926-01-28,Nuuk,Sermersooq,GRL,Denmark,NaN,NaN,1996-04-09
51844,52206,Freddy Brooks,1969-08-10,Guantánamo,Guantánamo,CUB,Cuba,187.0,84.0,NaN
61463,61912,Freddy Ehrström,1925-08-29,Helsinki,Uusimaa,FIN,Finland,178.0,70.0,NaN
64723,65211,Freddy Herbrand,1944-06-01,Malmedy,Liège,BEL,Belgium,190.0,88.0,NaN
82816,83473,Freddy Mayola,1977-11-01,La Habana (Havana),Ciudad de La Habana,CUB,Cuba,176.0,74.0,NaN
90682,91405,Freddy Suárez,1971-10-20,Güines,Mayabeque,CUB,Cuba,178.0,75.0,NaN
91388,92117,Freddy Mansveld,1911-08-02,NaN,NaN,NaN,Belgium,NaN,NaN,NaN
94637,95404,Freddy Mésot,1905-05-25,Sint-Niklaas,Oost-Vlaanderen,BEL,Belgium,174.0,NaN,1979-10-31
96158,96933,Freddy Romano,1966-07-25,Bern,Bern,SUI,Italy,178.0,70.0,NaN
97116,97898,Freddy Streun,1925-06-17,Bern,Bern,SUI,Switzerland,NaN,NaN,2019-11-26
100478,101328,Freddy Schwienbacher,1975-08-03,Merano,Bolzano-Bozen,ITA,Italy,181.0,77.0,NaN
108403,109554,Freddy González,1977-07-10,Cumaná,Sucre,VEN,Venezuela,160.0,60.0,NaN
110096,111304,Freddy Adu,1989-06-02,Tema,Greater Accra,GHA,United States,170.0,66.0,NaN
113059,114348,Freddy Cedeño,1981-09-10,Caracas,Distrito Capital,VEN,Venezuela,205.0,95.0,NaN
130801,133549,Freddy Figueroa,1994-11-26,Guayaquil,Guayas,ECU,Ecuador,192.0,100.0,NaN
131620,134434,B. Sumeeth Reddy,1991-09-26,Gungal,Andhra Pradesh,IND,India,182.0,64.0,NaN
133499,136438,Freddy Mezones,1987-09-24,Caracas,Distrito Capital,VEN,Venezuela,170.0,68.0,NaN
140259,143762,Satwiksairaj Rankireddy,2000-08-13,NaN,NaN,NaN,India,NaN,NaN,NaN